#!/usr/bin/env tsx
/**
 * Generates `src/index.generated.ts` from `scripts/api-registry.ts`.
 *
 * Modes:
 *   - `legacy`:        single-line typed re-export with `as unknown as` cast
 *   - `legacy-direct`: single-line typed re-export, no cast (the source is already typed)
 *   - `modern`:        three overloads (callback / InspectOptions / InspectEnvelopeOptions)
 *                      wired through wrapInspectFunction
 *   - `hybrid`:        modern overloads + a hand-written legacy positional overload + dispatcher body
 *
 * Run as `npm run codegen:api` to regenerate, or `--check` to fail if the file is stale.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { apiRegistry, type RegistryEntry } from './api-registry';

const HEADER = `// AUTOGENERATED by scripts/codegen-public-api.ts — do not edit by hand.
// Edit scripts/api-registry.ts and run \`npm run codegen:api\` to regenerate.

import * as util from './util';
import * as systemModule from './system';
import * as osInfoModule from './osinfo';
import * as cpuModule from './cpu';
import * as memoryModule from './memory';
import * as graphicsModule from './graphics';
import * as filesystemModule from './filesystem';
import * as networkModule from './network';
import * as wifiModule from './wifi';
import * as processesModule from './processes';
import * as usersModule from './users';
import * as internetModule from './internet';
import * as dockerModule from './docker';
import * as vboxModule from './virtualbox';
import * as printerModule from './printer';
import * as usbModule from './usb';
import * as audioModule from './audio';
import * as bluetoothModule from './bluetooth';
import { wrapInspectFunction, normalizeOptions, withInspectOptions } from './wrap';
import type {
  AudioData,
  BaseboardData,
  BiosData,
  BluetoothDeviceData,
  BlockDevicesData,
  Callback,
  ChassisData,
  CpuCacheData,
  CpuCurrentSpeedData,
  CpuData,
  CpuTemperatureData,
  CurrentLoadData,
  DiskLayoutData,
  DisksIoData,
  DockerContainerData,
  DockerContainerProcessData,
  DockerContainerStatsData,
  DockerImageData,
  DockerInfoData,
  DockerVolumeData,
  FsOpenFilesData,
  FsSizeData,
  FsStatsData,
  GraphicsData,
  InetChecksiteData,
  InspectEnvelope,
  InspectEnvelopeOptions,
  InspectOptions,
  MaybeUnsupported,
  MemData,
  MemLayoutData,
  NetworkConnectionsData,
  NetworkInterfacesData,
  NetworkStatsData,
  OsData,
  PrinterData,
  ProcessesData,
  ProcessesProcessLoadData,
  ServicesData,
  SystemData,
  UsbData,
  UserData,
  UuidData,
  VboxInfoData,
  VersionData,
  WifiConnectionData,
  WifiInterfaceData,
  WifiNetworkData
} from './types';
`;

function emitLegacy(name: string, signature: string, src: string): string {
  return `export const ${name}: ${signature} = ${src} as unknown as ${signature};`;
}

function emitLegacyDirect(name: string, signature: string, src: string): string {
  return `export const ${name}: ${signature} = ${src};`;
}

// JSDoc emitted on every callback-style overload — IDE strikethrough + warning,
// but no runtime change. Signals v2.0 direction without breaking v1.x consumers.
const CALLBACK_DEPRECATION = '/** @deprecated Pass an InspectOptions object and consume the returned Promise. The callback overload will be removed in v2.0. */';
const POSITIONAL_DEPRECATION = (paramHint: string) =>
  `/** @deprecated Use the InspectOptions object form instead (e.g. ${paramHint}). The positional form will be removed in v2.0. */`;

function emitModern(name: string, dataType: string, src: string, callForm: string): string {
  return [
    CALLBACK_DEPRECATION,
    `export function ${name}(callback?: Callback<${dataType}>): Promise<${dataType}>;`,
    `export function ${name}(options?: InspectOptions, callback?: Callback<${dataType}>): Promise<${dataType}>;`,
    `export function ${name}(options: InspectEnvelopeOptions, callback?: Callback<InspectEnvelope<${dataType}>>): Promise<InspectEnvelope<${dataType}>>;`,
    `export function ${name}(options?: any, callback?: any): Promise<${dataType} | InspectEnvelope<${dataType}>> {`,
    `  return wrapInspectFunction<${dataType}>('${name}', () => ${callForm}, options, callback);`,
    `}`
  ].join('\n');
}

function emitHybridFsSize(): string {
  const dataType = 'FsSizeData[]';
  return [
    CALLBACK_DEPRECATION,
    `export function fsSize(callback?: Callback<${dataType}>): Promise<${dataType}>;`,
    `export function fsSize(options?: InspectOptions, callback?: Callback<${dataType}>): Promise<${dataType}>;`,
    `export function fsSize(options: InspectEnvelopeOptions, callback?: Callback<InspectEnvelope<${dataType}>>): Promise<InspectEnvelope<${dataType}>>;`,
    POSITIONAL_DEPRECATION('{ drive: "/" }'),
    `export function fsSize(drive?: string | Callback<${dataType}>, callback?: Callback<${dataType}>): Promise<${dataType}>;`,
    `export function fsSize(optionsOrDrive?: any, callback?: any): Promise<${dataType} | InspectEnvelope<${dataType}>> {`,
    `  if (typeof optionsOrDrive === 'string') {`,
    `    return filesystemModule.fsSize(optionsOrDrive, callback) as Promise<${dataType} | InspectEnvelope<${dataType}>>;`,
    `  }`,
    `  const normalized = normalizeOptions(optionsOrDrive, callback);`,
    `  return withInspectOptions('fsSize', () => filesystemModule.fsSize(undefined, undefined), normalized.options, normalized.callback) as Promise<`,
    `    ${dataType} | InspectEnvelope<${dataType}>`,
    `  >;`,
    `}`
  ].join('\n');
}

function emitHybridNetworkInterfaces(): string {
  const dataType = 'NetworkInterfacesData[]';
  return [
    POSITIONAL_DEPRECATION('{ rescan: true, defaultString: "..." }'),
    `export function networkInterfaces(callback?: Callback<${dataType}> | boolean | string, rescan?: boolean, defaultString?: string): Promise<${dataType}>;`,
    `export function networkInterfaces(options?: InspectOptions, callback?: Callback<${dataType}>): Promise<${dataType}>;`,
    `export function networkInterfaces(options: InspectEnvelopeOptions, callback?: Callback<InspectEnvelope<${dataType}>>): Promise<InspectEnvelope<${dataType}>>;`,
    `export function networkInterfaces(optionsOrCallback?: any, rescanOrCallback?: any, defaultString?: string): Promise<${dataType} | InspectEnvelope<${dataType}>> {`,
    `  if (typeof optionsOrCallback === 'boolean' || typeof optionsOrCallback === 'string' || (optionsOrCallback && util.isFunction(optionsOrCallback))) {`,
    `    return networkModule.networkInterfaces(optionsOrCallback, rescanOrCallback, defaultString) as Promise<`,
    `      ${dataType} | InspectEnvelope<${dataType}>`,
    `    >;`,
    `  }`,
    `  const normalized = normalizeOptions(optionsOrCallback, rescanOrCallback);`,
    `  return withInspectOptions('networkInterfaces', () => networkModule.networkInterfaces(undefined, undefined, undefined), normalized.options, normalized.callback) as Promise<`,
    `    ${dataType} | InspectEnvelope<${dataType}>`,
    `  >;`,
    `}`
  ].join('\n');
}

function emitEntry(entry: RegistryEntry): string {
  const src = `${entry.module}.${entry.fn}`;
  switch (entry.mode) {
    case 'legacy':
      return emitLegacy(entry.name, entry.signature, src);
    case 'legacy-direct':
      return emitLegacyDirect(entry.name, entry.signature, src);
    case 'modern': {
      const callForm = entry.callForm ?? `${src}(undefined)`;
      return emitModern(entry.name, entry.dataType, src, callForm);
    }
    case 'hybrid':
      if (entry.name === 'fsSize') return emitHybridFsSize();
      if (entry.name === 'networkInterfaces') return emitHybridNetworkInterfaces();
      throw new Error(`Hybrid template missing for: ${entry.name}`);
  }
}

function generate(): string {
  const blocks = apiRegistry.map(emitEntry);
  return HEADER + '\n' + blocks.join('\n\n') + '\n';
}

// Normalise line endings so a Windows checkout (CRLF) compares equal to the
// generated string (LF). Without this, the freshness check fails on Windows
// CI even when the file is byte-identical modulo line endings.
function normalize(s: string): string {
  return s.replace(/\r\n/g, '\n').trim();
}

function main() {
  const targetPath = resolve(__dirname, '..', 'src', 'index.generated.ts');
  const next = generate();
  const checkMode = process.argv.includes('--check');
  if (checkMode) {
    const current = readFileSync(targetPath, 'utf8');
    if (normalize(current) !== normalize(next)) {
      process.stderr.write(`src/index.generated.ts is stale.\nRun \`npm run codegen:api\` to refresh.\n`);
      process.exit(1);
    }
    process.stdout.write('src/index.generated.ts is up to date.\n');
    return;
  }
  writeFileSync(targetPath, next);
  process.stdout.write(`Wrote ${targetPath} (${apiRegistry.length} entries).\n`);
}

main();
