#!/usr/bin/env tsx
/**
 * Regenerates `src/bluetoothVendors.ts` from the canonical Bluetooth SIG
 * YAML at:
 *
 *   https://bitbucket.org/bluetooth-SIG/public/raw/main/assigned_numbers/company_identifiers/company_identifiers.yaml
 *
 * Usage:
 *   npm run codegen:bluetooth-vendors            # write the file
 *   npm run codegen:bluetooth-vendors:check      # exit non-zero if file would change
 *
 * The YAML format is flat key/value with single-quoted name strings (with
 * `''` escaping inner quotes), so we parse with a focused regex rather
 * than pulling in a YAML dep — keeping the package zero-runtime-dep.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const SOURCE_URL = 'https://bitbucket.org/bluetooth-SIG/public/raw/main/assigned_numbers/company_identifiers/company_identifiers.yaml';
const TARGET_PATH = resolve(__dirname, '..', 'src', 'bluetoothVendors.ts');
const MIN_EXPECTED_ENTRIES = 1000;

interface VendorEntry {
  id: number;
  name: string;
}

async function fetchYaml(): Promise<string> {
  const response = await fetch(SOURCE_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${SOURCE_URL}: ${response.status} ${response.statusText}`);
  }
  return response.text();
}

const ENTRY_RE = /-\s*value:\s*(0x[0-9A-Fa-f]+)\s*\n\s+name:\s*'((?:[^']|'')*)'/g;

export function parseCompanyIdentifiersYaml(input: string): VendorEntry[] {
  const out: VendorEntry[] = [];
  for (const match of input.matchAll(ENTRY_RE)) {
    const id = Number.parseInt(match[1], 16);
    if (!Number.isFinite(id)) continue;
    const name = match[2].replaceAll("''", "'");
    out.push({ id, name });
  }
  out.sort((a, b) => a.id - b.id);
  return out;
}

function emitFile(entries: VendorEntry[], fetchedAt: string): string {
  const header = [
    '// AUTOGENERATED by scripts/generate-bluetooth-vendors.ts — do not edit by hand.',
    '//',
    `// Source:  ${SOURCE_URL}`,
    `// Fetched: ${fetchedAt}`,
    `// Entries: ${entries.length}`,
    '//',
    '// Run `npm run codegen:bluetooth-vendors` to refresh.',
    '',
    'export const bluetoothVendors: Record<number, string> = {'
  ].join('\n');
  const body = entries
    .map((entry) => `  ${entry.id}: ${JSON.stringify(entry.name)}`)
    .join(',\n');
  return `${header}\n${body}\n};\n\nexport default bluetoothVendors;\n`;
}

async function main(): Promise<void> {
  const checkMode = process.argv.includes('--check');
  const yaml = await fetchYaml();
  const entries = parseCompanyIdentifiersYaml(yaml);
  if (entries.length < MIN_EXPECTED_ENTRIES) {
    throw new Error(`Parsed only ${entries.length} entries (expected ≥${MIN_EXPECTED_ENTRIES}). The upstream format may have changed; refusing to overwrite.`);
  }
  const fetchedAt = new Date().toISOString().slice(0, 10);
  const next = emitFile(entries, fetchedAt);
  if (checkMode) {
    let current = '';
    try {
      current = readFileSync(TARGET_PATH, 'utf8');
    } catch {
      // file missing — treat as stale
    }
    // Allow the Fetched: date to differ; only flag content drift.
    const stripDate = (s: string) => s.replace(/^\/\/ Fetched:.*$/m, '// Fetched: <DATE>');
    if (stripDate(current) !== stripDate(next)) {
      process.stderr.write(`src/bluetoothVendors.ts is stale (${entries.length} upstream entries).\nRun \`npm run codegen:bluetooth-vendors\` to refresh.\n`);
      process.exit(1);
    }
    process.stdout.write(`src/bluetoothVendors.ts is up to date (${entries.length} entries).\n`);
    return;
  }
  writeFileSync(TARGET_PATH, next);
  process.stdout.write(`Wrote ${TARGET_PATH} with ${entries.length} entries.\n`);
}

main().catch((err) => {
  process.stderr.write(`generate-bluetooth-vendors failed: ${(err as Error).message}\n`);
  process.exit(1);
});
