#!/usr/bin/env node
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const pkg = require('../package.json');

const target = path.resolve(__dirname, '..', 'src', 'version.generated.ts');
const contents = `// AUTOGENERATED by scripts/write-version.js — do not edit.\n// Run \`npm run prebuild\` to refresh.\nexport const VERSION = '${pkg.version}';\n`;
fs.writeFileSync(target, contents);
