// AUTOGENERATED by scripts/codegen-public-api.ts — do not edit by hand.
// Edit scripts/api-registry.ts and run `npm run codegen:api` to regenerate.

import * as util from './util';
import * as systemModule from './system';
import * as osInfoModule from './osinfo';
import * as cpuModule from './cpu';
import * as memoryModule from './memory';
import * as graphicsModule from './graphics';
import * as filesystemModule from './filesystem';
import * as networkModule from './network';
import * as wifiModule from './wifi';
import * as processesModule from './processes';
import * as usersModule from './users';
import * as internetModule from './internet';
import * as dockerModule from './docker';
import * as vboxModule from './virtualbox';
import * as printerModule from './printer';
import * as usbModule from './usb';
import * as audioModule from './audio';
import * as bluetoothModule from './bluetooth';
import { wrapInspectFunction, normalizeOptions, withInspectOptions } from './wrap';
import type {
  AudioData,
  BaseboardData,
  BiosData,
  BluetoothDeviceData,
  BlockDevicesData,
  Callback,
  ChassisData,
  CpuCacheData,
  CpuCurrentSpeedData,
  CpuData,
  CpuTemperatureData,
  CurrentLoadData,
  DiskLayoutData,
  DisksIoData,
  DockerContainerData,
  DockerContainerProcessData,
  DockerContainerStatsData,
  DockerImageData,
  DockerInfoData,
  DockerVolumeData,
  FsOpenFilesData,
  FsSizeData,
  FsStatsData,
  GraphicsData,
  InetChecksiteData,
  InspectEnvelope,
  InspectEnvelopeOptions,
  InspectOptions,
  MaybeUnsupported,
  MemData,
  MemLayoutData,
  NetworkConnectionsData,
  NetworkInterfacesData,
  NetworkStatsData,
  OsData,
  PrinterData,
  ProcessesData,
  ProcessesProcessLoadData,
  ServicesData,
  SystemData,
  UsbData,
  UserData,
  UuidData,
  VboxInfoData,
  VersionData,
  WifiConnectionData,
  WifiInterfaceData,
  WifiNetworkData
} from './types';

export const system: (callback?: Callback<SystemData>) => Promise<SystemData> = systemModule.system;

export const bios: (callback?: Callback<BiosData>) => Promise<BiosData> = systemModule.bios;

export const baseboard: (callback?: Callback<BaseboardData>) => Promise<BaseboardData> = systemModule.baseboard;

export const chassis: (callback?: Callback<ChassisData>) => Promise<ChassisData> = systemModule.chassis;

export function osInfo(callback?: Callback<OsData>): Promise<OsData>;
export function osInfo(options?: InspectOptions, callback?: Callback<OsData>): Promise<OsData>;
export function osInfo(options: InspectEnvelopeOptions, callback?: Callback<InspectEnvelope<OsData>>): Promise<InspectEnvelope<OsData>>;
export function osInfo(options?: any, callback?: any): Promise<OsData | InspectEnvelope<OsData>> {
  return wrapInspectFunction<OsData>('osInfo', () => osInfoModule.osInfo(undefined), options, callback);
}

export const versions: (apps?: string | Callback<VersionData>, callback?: Callback<VersionData>) => Promise<VersionData> = osInfoModule.versions as unknown as (apps?: string | Callback<VersionData>, callback?: Callback<VersionData>) => Promise<VersionData>;

export const shell: (callback?: Callback<string>) => Promise<string> = osInfoModule.shell as unknown as (callback?: Callback<string>) => Promise<string>;

export const uuid: (callback?: Callback<UuidData>) => Promise<UuidData> = osInfoModule.uuid as unknown as (callback?: Callback<UuidData>) => Promise<UuidData>;

export function cpu(callback?: Callback<CpuData>): Promise<CpuData>;
export function cpu(options?: InspectOptions, callback?: Callback<CpuData>): Promise<CpuData>;
export function cpu(options: InspectEnvelopeOptions, callback?: Callback<InspectEnvelope<CpuData>>): Promise<InspectEnvelope<CpuData>>;
export function cpu(options?: any, callback?: any): Promise<CpuData | InspectEnvelope<CpuData>> {
  return wrapInspectFunction<CpuData>('cpu', () => cpuModule.cpu(undefined), options, callback);
}

export const cpuFlags: (callback?: Callback<string>) => Promise<string> = cpuModule.cpuFlags as unknown as (callback?: Callback<string>) => Promise<string>;

export const cpuCache: (callback?: Callback<CpuCacheData>) => Promise<CpuCacheData> = cpuModule.cpuCache as unknown as (callback?: Callback<CpuCacheData>) => Promise<CpuCacheData>;

export const cpuCurrentSpeed: (callback?: Callback<CpuCurrentSpeedData>) => Promise<CpuCurrentSpeedData> = cpuModule.cpuCurrentSpeed as unknown as (callback?: Callback<CpuCurrentSpeedData>) => Promise<CpuCurrentSpeedData>;

export const cpuTemperature: (callback?: Callback<CpuTemperatureData>) => Promise<CpuTemperatureData> = cpuModule.cpuTemperature as unknown as (callback?: Callback<CpuTemperatureData>) => Promise<CpuTemperatureData>;

export const currentLoad: (callback?: Callback<CurrentLoadData>) => Promise<CurrentLoadData> = cpuModule.currentLoad as unknown as (callback?: Callback<CurrentLoadData>) => Promise<CurrentLoadData>;

export const fullLoad: (callback?: Callback<number>) => Promise<number> = cpuModule.fullLoad as unknown as (callback?: Callback<number>) => Promise<number>;

export function mem(callback?: Callback<MemData>): Promise<MemData>;
export function mem(options?: InspectOptions, callback?: Callback<MemData>): Promise<MemData>;
export function mem(options: InspectEnvelopeOptions, callback?: Callback<InspectEnvelope<MemData>>): Promise<InspectEnvelope<MemData>>;
export function mem(options?: any, callback?: any): Promise<MemData | InspectEnvelope<MemData>> {
  return wrapInspectFunction<MemData>('mem', () => memoryModule.mem(undefined), options, callback);
}

export const memLayout: (callback?: Callback<MemLayoutData[]>) => Promise<MemLayoutData[]> = memoryModule.memLayout;

export function graphics(callback?: Callback<MaybeUnsupported<GraphicsData>>): Promise<MaybeUnsupported<GraphicsData>>;
export function graphics(options?: InspectOptions, callback?: Callback<MaybeUnsupported<GraphicsData>>): Promise<MaybeUnsupported<GraphicsData>>;
export function graphics(options: InspectEnvelopeOptions, callback?: Callback<InspectEnvelope<MaybeUnsupported<GraphicsData>>>): Promise<InspectEnvelope<MaybeUnsupported<GraphicsData>>>;
export function graphics(options?: any, callback?: any): Promise<MaybeUnsupported<GraphicsData> | InspectEnvelope<MaybeUnsupported<GraphicsData>>> {
  return wrapInspectFunction<MaybeUnsupported<GraphicsData>>('graphics', () => graphicsModule.graphics(undefined), options, callback);
}

export function fsSize(callback?: Callback<FsSizeData[]>): Promise<FsSizeData[]>;
export function fsSize(options?: InspectOptions, callback?: Callback<FsSizeData[]>): Promise<FsSizeData[]>;
export function fsSize(options: InspectEnvelopeOptions, callback?: Callback<InspectEnvelope<FsSizeData[]>>): Promise<InspectEnvelope<FsSizeData[]>>;
export function fsSize(drive?: string | Callback<FsSizeData[]>, callback?: Callback<FsSizeData[]>): Promise<FsSizeData[]>;
export function fsSize(optionsOrDrive?: any, callback?: any): Promise<FsSizeData[] | InspectEnvelope<FsSizeData[]>> {
  if (typeof optionsOrDrive === 'string') {
    return filesystemModule.fsSize(optionsOrDrive, callback) as Promise<FsSizeData[] | InspectEnvelope<FsSizeData[]>>;
  }
  const normalized = normalizeOptions(optionsOrDrive, callback);
  return withInspectOptions('fsSize', () => filesystemModule.fsSize(undefined, undefined), normalized.options, normalized.callback) as Promise<
    FsSizeData[] | InspectEnvelope<FsSizeData[]>
  >;
}

export const fsOpenFiles: (callback?: Callback<FsOpenFilesData>) => Promise<FsOpenFilesData> = filesystemModule.fsOpenFiles as unknown as (callback?: Callback<FsOpenFilesData>) => Promise<FsOpenFilesData>;

export const blockDevices: (callback?: Callback<BlockDevicesData[]>) => Promise<BlockDevicesData[]> = filesystemModule.blockDevices as unknown as (callback?: Callback<BlockDevicesData[]>) => Promise<BlockDevicesData[]>;

export const fsStats: (callback?: Callback<FsStatsData>) => Promise<FsStatsData> = filesystemModule.fsStats as unknown as (callback?: Callback<FsStatsData>) => Promise<FsStatsData>;

export const disksIO: (callback?: Callback<DisksIoData>) => Promise<DisksIoData> = filesystemModule.disksIO as unknown as (callback?: Callback<DisksIoData>) => Promise<DisksIoData>;

export function diskLayout(callback?: Callback<DiskLayoutData[]>): Promise<DiskLayoutData[]>;
export function diskLayout(options?: InspectOptions, callback?: Callback<DiskLayoutData[]>): Promise<DiskLayoutData[]>;
export function diskLayout(options: InspectEnvelopeOptions, callback?: Callback<InspectEnvelope<DiskLayoutData[]>>): Promise<InspectEnvelope<DiskLayoutData[]>>;
export function diskLayout(options?: any, callback?: any): Promise<DiskLayoutData[] | InspectEnvelope<DiskLayoutData[]>> {
  return wrapInspectFunction<DiskLayoutData[]>('diskLayout', () => filesystemModule.diskLayout(undefined), options, callback);
}

export const networkInterfaceDefault: (callback?: Callback<string>) => Promise<string> = networkModule.networkInterfaceDefault as unknown as (callback?: Callback<string>) => Promise<string>;

export const networkGatewayDefault: (callback?: Callback<string>) => Promise<string> = networkModule.networkGatewayDefault as unknown as (callback?: Callback<string>) => Promise<string>;

export function networkInterfaces(callback?: Callback<NetworkInterfacesData[]> | boolean | string, rescan?: boolean, defaultString?: string): Promise<NetworkInterfacesData[]>;
export function networkInterfaces(options?: InspectOptions, callback?: Callback<NetworkInterfacesData[]>): Promise<NetworkInterfacesData[]>;
export function networkInterfaces(options: InspectEnvelopeOptions, callback?: Callback<InspectEnvelope<NetworkInterfacesData[]>>): Promise<InspectEnvelope<NetworkInterfacesData[]>>;
export function networkInterfaces(optionsOrCallback?: any, rescanOrCallback?: any, defaultString?: string): Promise<NetworkInterfacesData[] | InspectEnvelope<NetworkInterfacesData[]>> {
  if (typeof optionsOrCallback === 'boolean' || typeof optionsOrCallback === 'string' || (optionsOrCallback && util.isFunction(optionsOrCallback))) {
    return networkModule.networkInterfaces(optionsOrCallback, rescanOrCallback, defaultString) as Promise<
      NetworkInterfacesData[] | InspectEnvelope<NetworkInterfacesData[]>
    >;
  }
  const normalized = normalizeOptions(optionsOrCallback, rescanOrCallback);
  return withInspectOptions('networkInterfaces', () => networkModule.networkInterfaces(undefined, undefined, undefined), normalized.options, normalized.callback) as Promise<
    NetworkInterfacesData[] | InspectEnvelope<NetworkInterfacesData[]>
  >;
}

export const networkStats: (ifaces?: string | Callback<NetworkStatsData[]>, callback?: Callback<NetworkStatsData[]>) => Promise<NetworkStatsData[]> = networkModule.networkStats as unknown as (ifaces?: string | Callback<NetworkStatsData[]>, callback?: Callback<NetworkStatsData[]>) => Promise<NetworkStatsData[]>;

export const networkConnections: (callback?: Callback<NetworkConnectionsData[]>) => Promise<NetworkConnectionsData[]> = networkModule.networkConnections as unknown as (callback?: Callback<NetworkConnectionsData[]>) => Promise<NetworkConnectionsData[]>;

export const wifiNetworks: (callback?: Callback<MaybeUnsupported<WifiNetworkData[]>>) => Promise<MaybeUnsupported<WifiNetworkData[]>> = wifiModule.wifiNetworks;

export const wifiInterfaces: (callback?: Callback<WifiInterfaceData[]>) => Promise<WifiInterfaceData[]> = wifiModule.wifiInterfaces;

export const wifiConnections: (callback?: Callback<WifiConnectionData[]>) => Promise<WifiConnectionData[]> = wifiModule.wifiConnections;

export const services: (srv?: string | Callback<ServicesData[]>, callback?: Callback<ServicesData[]>) => Promise<ServicesData[]> = processesModule.services as unknown as (srv?: string | Callback<ServicesData[]>, callback?: Callback<ServicesData[]>) => Promise<ServicesData[]>;

export function processes(callback?: Callback<ProcessesData>): Promise<ProcessesData>;
export function processes(options?: InspectOptions, callback?: Callback<ProcessesData>): Promise<ProcessesData>;
export function processes(options: InspectEnvelopeOptions, callback?: Callback<InspectEnvelope<ProcessesData>>): Promise<InspectEnvelope<ProcessesData>>;
export function processes(options?: any, callback?: any): Promise<ProcessesData | InspectEnvelope<ProcessesData>> {
  return wrapInspectFunction<ProcessesData>('processes', () => processesModule.processes(undefined), options, callback);
}

export const processLoad: (proc?: string | Callback<ProcessesProcessLoadData[]>, callback?: Callback<ProcessesProcessLoadData[]>) => Promise<ProcessesProcessLoadData[]> = processesModule.processLoad as unknown as (proc?: string | Callback<ProcessesProcessLoadData[]>, callback?: Callback<ProcessesProcessLoadData[]>) => Promise<ProcessesProcessLoadData[]>;

export const users: (callback?: Callback<UserData[]>) => Promise<UserData[]> = usersModule.users;

export const inetChecksite: (url: string, callback?: Callback<InetChecksiteData>) => Promise<InetChecksiteData> = internetModule.inetChecksite;

export const inetLatency: (host?: string | Callback<number | null>, callback?: Callback<number | null>) => Promise<number | null> = internetModule.inetLatency;

export const dockerInfo: (callback?: Callback<DockerInfoData>) => Promise<DockerInfoData> = dockerModule.dockerInfo;

export const dockerImages: (all?: boolean | string | Callback<DockerImageData[]>, callback?: Callback<DockerImageData[]>) => Promise<DockerImageData[]> = dockerModule.dockerImages;

export const dockerContainers: (all?: boolean | string | Callback<DockerContainerData[]>, callback?: Callback<DockerContainerData[]>) => Promise<DockerContainerData[]> = dockerModule.dockerContainers;

export const dockerContainerStats: (containerIDs?: string | Callback<DockerContainerStatsData[]>, callback?: Callback<DockerContainerStatsData[]>) => Promise<DockerContainerStatsData[]> = dockerModule.dockerContainerStats;

export const dockerContainerProcesses: (containerID?: string, callback?: Callback<DockerContainerProcessData[]>) => Promise<DockerContainerProcessData[]> = dockerModule.dockerContainerProcesses;

export const dockerVolumes: (callback?: Callback<DockerVolumeData[]>) => Promise<DockerVolumeData[]> = dockerModule.dockerVolumes;

export function dockerAll(callback?: Callback<any[]>): Promise<any[]>;
export function dockerAll(options?: InspectOptions, callback?: Callback<any[]>): Promise<any[]>;
export function dockerAll(options: InspectEnvelopeOptions, callback?: Callback<InspectEnvelope<any[]>>): Promise<InspectEnvelope<any[]>>;
export function dockerAll(options?: any, callback?: any): Promise<any[] | InspectEnvelope<any[]>> {
  return wrapInspectFunction<any[]>('dockerAll', () => dockerModule.dockerAll(undefined), options, callback);
}

export const vboxInfo: (callback?: Callback<VboxInfoData[]>) => Promise<VboxInfoData[]> = vboxModule.vboxInfo;

export const printer: (callback?: Callback<MaybeUnsupported<PrinterData[]>>) => Promise<MaybeUnsupported<PrinterData[]>> = printerModule.printer;

export const usb: (callback?: Callback<MaybeUnsupported<UsbData[]>>) => Promise<MaybeUnsupported<UsbData[]>> = usbModule.usb;

export const audio: (callback?: Callback<MaybeUnsupported<AudioData[]>>) => Promise<MaybeUnsupported<AudioData[]>> = audioModule.audio;

export const bluetoothDevices: (callback?: Callback<MaybeUnsupported<BluetoothDeviceData[]>>) => Promise<MaybeUnsupported<BluetoothDeviceData[]>> = bluetoothModule.bluetoothDevices;
